View(NOV22_MWDISCHARGE_DATA)
dim(NOV22_MWDISCHARGE_DATA)
attributes(NOV22_MWDISCHARGE_DATA)
class(NOV22_MWDISCHARGE_DATA)
typeof(NOV22_MWDISCHARGE_DATA)
str(NOV22_MWDISCHARGE_DATA)
head(NOV22_MWDISCHARGE_DATA,10)
tail(NOV22_MWDISCHARGE_DATA,10)
 